# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/joan-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter joan l01k,$(TARGET_DEVICE)),)

endif
